name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up cmake
        uses: lukka/get-cmake@v3.21.2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtest-dev

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./test_calculator

  deploy:  # This must be inside `jobs`
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: echo "Deploying to production server"

